include: package:lints/recommended.yaml

analyzer:
  errors:
    unused_import: warning
    unused_local_variable: warning
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - avoid_print
