// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Duxt

import 'package:jaspr_router/jaspr_router.dart';

import 'pages/index.dart' as page_indexpage;
import 'pages/api/index.dart' as page_apipage;
import 'pages/duxt-ui/index.dart' as page_duxtuipage;
import 'pages/components/index.dart' as page_componentspage;
import 'pages/components/card.dart' as page_componentscardpage;
import 'pages/getting-started/index.dart' as page_gettingstartedpage;
import 'pages/duxt-ui/theming.dart' as page_duxtuithemingpage;
import 'pages/components/input.dart' as page_componentsinputpage;
import 'pages/components/button.dart' as page_componentsbuttonpage;
import 'pages/duxt-ui/components.dart' as page_duxtuicomponentspage;
import 'pages/duxt-ui/installation.dart' as page_duxtuiinstallationpage;
import 'pages/getting-started/quick-start.dart' as page_gettingstartedquickstartpage;

/// Generated routes from modules
final generatedRoutes = <Route>[
  Route(
    path: '/',
    builder: (context, state) {
      return const page_indexpage.IndexPage();
    },
  ),
  Route(
    path: '/api',
    builder: (context, state) {
      return const page_apipage.ApiPage();
    },
  ),
  Route(
    path: '/duxt-ui',
    builder: (context, state) {
      return const page_duxtuipage.DuxtUiPage();
    },
  ),
  Route(
    path: '/components',
    builder: (context, state) {
      return const page_componentspage.ComponentsPage();
    },
  ),
  Route(
    path: '/components/card',
    builder: (context, state) {
      return const page_componentscardpage.ComponentsCardPage();
    },
  ),
  Route(
    path: '/getting-started',
    builder: (context, state) {
      return const page_gettingstartedpage.GettingStartedPage();
    },
  ),
  Route(
    path: '/duxt-ui/theming',
    builder: (context, state) {
      return const page_duxtuithemingpage.DuxtUiThemingPage();
    },
  ),
  Route(
    path: '/components/input',
    builder: (context, state) {
      return const page_componentsinputpage.ComponentsInputPage();
    },
  ),
  Route(
    path: '/components/button',
    builder: (context, state) {
      return const page_componentsbuttonpage.ComponentsButtonPage();
    },
  ),
  Route(
    path: '/duxt-ui/components',
    builder: (context, state) {
      return const page_duxtuicomponentspage.DuxtUiComponentsPage();
    },
  ),
  Route(
    path: '/duxt-ui/installation',
    builder: (context, state) {
      return const page_duxtuiinstallationpage.DuxtUiInstallationPage();
    },
  ),
  Route(
    path: '/getting-started/quick-start',
    builder: (context, state) {
      return const page_gettingstartedquickstartpage.GettingStartedQuickStartPage();
    },
  ),
];
