/// The entrypoint for the **server** environment.
///
/// The [main] method will only be executed on the server during pre-rendering.
/// To run code on the client, check the `main.client.dart` file.
library;

// Server-specific Jaspr import.
import 'package:jaspr/dom.dart';
import 'package:jaspr/server.dart';

import 'package:jaspr_content/components/callout.dart';
import 'package:jaspr_content/components/code_block.dart';
import 'package:jaspr_content/components/image.dart';
import 'package:jaspr_content/jaspr_content.dart';
import 'package:jaspr_content/theme.dart';

import 'layouts/duxt_layout.dart';
import 'layouts/ui_layout.dart';
import 'layouts/landing_layout.dart';

// This file is generated automatically by Jaspr, do not remove or edit.
import 'main.server.options.dart';

void main() {
  // Initializes the server environment with the generated default options.
  Jaspr.initializeApp(
    options: defaultServerOptions,
  );

  // Starts the app.
  runApp(
    Document(
      lang: 'en',
      head: [
        // Google Fonts - Nunito
        link(href: 'https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;500;600;700&display=swap', rel: 'stylesheet'),
        // Link the styles.css file, this will be generated by the tailwind integration.
        link(href: 'styles.css', rel: 'stylesheet'),
      ],
      body: ContentApp(
        // Enables mustache templating inside the markdown files.
        templateEngine: MustacheTemplateEngine(),
        parsers: [
          MarkdownParser(),
        ],
        extensions: [
          // Adds heading anchors to each heading.
          HeadingAnchorsExtension(),
          // Generates a table of contents for each page.
          TableOfContentsExtension(),
        ],
        components: [
          // The <Info> block and other callouts.
          Callout(),
          // Adds syntax highlighting to code blocks.
          CodeBlock(),
          // Adds zooming and caption support to images.
          Image(zoom: true),
        ],
        layouts: [
          // Duxt Framework documentation
          DuxtLayout(),
          // Duxt UI documentation
          UiLayout(),
          // Landing page layout (for index page)
          LandingLayout(),
        ],
        theme: ContentTheme(
          // Duxt cyan theme color
          primary: ThemeColor(ThemeColors.cyan.$500, dark: ThemeColors.cyan.$400),
          background: ThemeColor(ThemeColors.slate.$50, dark: ThemeColors.zinc.$950),
          colors: [
            ContentColors.quoteBorders.apply(ThemeColors.cyan.$500),
          ],
        ),
      ),
    ),
  );
}
